import JSZip from 'jszip';

/**
 * Independent React Website Exporter
 * Generates a complete, standalone, production-ready React + Vite project
 * containing client branding, products, media assets, SEO metadata, and deployment configs.
 */
export async function exportStandaloneWebsite(project, template) {
  const zip = new JSZip();
  const projectName = (project.name || 'client-website').toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  const clientBrand = project.brand || {};
  const products = project.products || [];
  const seo = project.seo || {};

  // 1. Generate package.json
  const isYoungWheels = template.id === 'youngwheels';
  const pkgJson = {
    name: projectName,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: isYoungWheels
      ? {
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          'lucide-react': '^0.441.0',
          motion: '^12.0.0',
          'canvas-confetti': '^1.9.4'
        }
      : {
          react: '^18.3.1',
          'react-dom': '^18.3.1',
          'react-router-dom': '^6.26.1',
          'lucide-react': '^0.441.0',
          ...(template.id === 'padmacables' ? { lenis: '^1.3.25' } : {}),
          ...(template.id === 'plazaclock' ? { 'framer-motion': '^11.3.31', 'locomotive-scroll': '^5.0.1' } : {})
        },
    devDependencies: {
      '@vitejs/plugin-react': '^4.3.1',
      vite: '^5.4.2'
    }
  };

  zip.file('package.json', JSON.stringify(pkgJson, null, 2));

  // 2. Generate vite.config.js
  const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    open: true
  }
});
`;
  zip.file('vite.config.js', viteConfig);

  // 3. Generate index.html with customized SEO
  const siteTitle = seo.title || `${clientBrand.name || 'Client Website'} — Official Site`;
  const siteDesc = seo.description || clientBrand.tagline || 'Engineered with precision and elegance.';
  const primaryColor = clientBrand.color || template.accentColor || '#3b82f6';

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${siteTitle}</title>
    <meta name="description" content="${siteDesc}" />
    <meta name="theme-color" content="${primaryColor}" />
    <meta property="og:title" content="${siteTitle}" />
    <meta property="og:description" content="${siteDesc}" />
    <meta property="og:type" content="website" />
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Oswald:wght@500;600;700&family=Cormorant+Garamond:wght@400;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
  zip.file('index.html', indexHtml);

  // 4. Generate SVG Favicon
  const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="8" fill="${primaryColor}"/>
  <text x="16" y="21" font-family="system-ui, sans-serif" font-weight="900" font-size="16" fill="#ffffff" text-anchor="middle">${(clientBrand.name || 'C')[0]}</text>
</svg>`;
  zip.file('public/favicon.svg', faviconSvg);

  // 5. Generate src/config/siteConfig.js
  const siteConfigContent = `/**
 * Standalone Client Website Configuration
 * Generated by Agency Website Builder Platform
 * Tier: ${template.tier.toUpperCase()} (${template.tierLabel})
 */
export const SITE_CONFIG = {
  templateId: ${JSON.stringify(template.id)},
  tier: ${JSON.stringify(template.tier)},
  client: {
    name: ${JSON.stringify(clientBrand.name || template.title)},
    tagline: ${JSON.stringify(clientBrand.tagline || template.tagline)},
    description: ${JSON.stringify(clientBrand.description || template.description)},
    phone: ${JSON.stringify(clientBrand.phone || '')},
    whatsapp: ${JSON.stringify(clientBrand.whatsapp || clientBrand.phone || '')},
    email: ${JSON.stringify(clientBrand.email || '')},
    address: ${JSON.stringify(clientBrand.address || '')},
    city: ${JSON.stringify(clientBrand.city || '')},
    themeMode: ${JSON.stringify(clientBrand.themeMode || 'dark')},
    primaryColor: ${JSON.stringify(primaryColor)},
    secondaryColor: ${JSON.stringify(clientBrand.secondaryColor || '#1e293b')},
    accentColor: ${JSON.stringify(clientBrand.accentColor || primaryColor)},
    logoUrl: ${JSON.stringify(clientBrand.logoUrl || '')}
  },
  content: ${JSON.stringify(project.content || {}, null, 2)},
  seo: {
    title: ${JSON.stringify(siteTitle)},
    description: ${JSON.stringify(siteDesc)}
  },
  products: ${JSON.stringify(products, null, 2)},
  routes: ${JSON.stringify(template.routes || [], null, 2)}
};
`;
  zip.file('src/config/siteConfig.js', siteConfigContent);

  // 6. Generate src/index.css
  const isLight = clientBrand.themeMode === 'light';
  const indexCss = `/* Client Website Design System */
:root {
  --primary: ${primaryColor};
  --accent: ${clientBrand.accentColor || template.accentColor || primaryColor};
  --bg-dark: ${isLight ? '#f8fafc' : (template.heroColor || '#0a0d14')};
  --text-main: ${isLight ? '#0f172a' : '#f1f5f9'};
  --text-muted: ${isLight ? '#64748b' : '#94a3b8'};
  --card-bg: ${isLight ? '#ffffff' : 'rgba(255, 255, 255, 0.03)'};
  --card-border: ${isLight ? 'rgba(0, 0, 0, 0.08)' : 'rgba(255, 255, 255, 0.08)'};
  --font-main: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: var(--font-main);
  background-color: var(--bg-dark);
  color: var(--text-main);
  line-height: 1.6;
  overflow-x: hidden;
}

a {
  color: inherit;
  text-decoration: none;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
}

.btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  background: var(--primary);
  color: #ffffff;
  padding: 12px 28px;
  border-radius: 9999px;
  font-weight: 600;
  font-size: 14px;
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
  box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.4);
}

.btn-primary:hover {
  transform: translateY(-2px);
  filter: brightness(1.1);
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 24px;
  margin: 40px 0;
}

.product-card {
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 16px;
  padding: 24px;
  transition: all 0.3s ease;
}

.product-card:hover {
  transform: translateY(-4px);
  border-color: var(--primary);
  background: rgba(255, 255, 255, 0.05);
}

.badge {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 9999px;
  background: rgba(255, 255, 255, 0.08);
  color: var(--primary);
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  margin-bottom: 12px;
}
`;
  zip.file('src/index.css', indexCss);

  // 7. Generate src/main.jsx
  const mainJsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
  zip.file('src/main.jsx', mainJsx);

  // 8. Generate src/App.jsx
  const appJsx = `import React, { useState } from 'react';
import { SITE_CONFIG } from './config/siteConfig';

function ProductCard({ prod, client }) {
  const images = (prod.images && prod.images.length > 0) ? prod.images : (prod.image ? [prod.image] : []);
  const [activeImg, setActiveImg] = useState(prod.image || images[0] || '');

  return (
    <div className="product-card">
      {activeImg && (
        <div style={{ width: '100%', height: 200, borderRadius: 12, overflow: 'hidden', background: client.themeMode === 'light' ? '#f1f5f9' : '#070a13', marginBottom: 14, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <img src={activeImg} alt={prod.name || prod.title} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} />
        </div>
      )}

      {/* Interactive Multi-Image Gallery Thumbnails */}
      {images.length > 1 && (
        <div style={{ display: 'flex', gap: 6, marginBottom: 14, overflowX: 'auto', paddingBottom: 4 }}>
          {images.map((imgUrl, i) => (
            <button
              key={i}
              type="button"
              onClick={() => setActiveImg(imgUrl)}
              style={{
                width: 38,
                height: 38,
                borderRadius: 8,
                overflow: 'hidden',
                padding: 0,
                border: activeImg === imgUrl ? \`2px solid \${client.primaryColor}\` : '1px solid rgba(255, 255, 255, 0.15)',
                background: '#070a13',
                cursor: 'pointer',
                flexShrink: 0
              }}
            >
              <img src={imgUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </button>
          ))}
        </div>
      )}

      {prod.chips && prod.chips.length > 0 && (
        <div style={{ display: 'flex', gap: 6, marginBottom: 12, flexWrap: 'wrap' }}>
          {prod.chips.map((c, i) => (
            <span key={i} style={{ fontSize: 10, background: 'rgba(255,255,255,0.08)', padding: '2px 8px', borderRadius: 4 }}>{c}</span>
          ))}
        </div>
      )}
      <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 6 }}>{prod.name || prod.title}</h3>
      <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>{prod.description}</p>
      {prod.price && (
        <div style={{ fontSize: 17, fontWeight: 800, color: client.primaryColor, marginBottom: 14 }}>{prod.price}</div>
      )}
      <a
        href={\`https://wa.me/\${(client.whatsapp || '').replace(/[^0-9]/g, '')}?text=Inquiring%20about%20\${encodeURIComponent(prod.name || prod.title)}\`}
        target="_blank"
        rel="noreferrer"
        style={{
          display: 'block',
          textAlign: 'center',
          padding: '10px 16px',
          borderRadius: 8,
          background: 'rgba(255, 255, 255, 0.05)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          fontSize: 13,
          fontWeight: 600,
          color: client.primaryColor
        }}
      >
        Request Quote &rarr;
      </a>
    </div>
  );
}

export default function App() {
  const { client, products, seo } = SITE_CONFIG;

  return (
    <div className="site-wrapper">
      {/* Header */}
      <header style={{
        position: 'sticky',
        top: 0,
        zIndex: 50,
        background: 'rgba(11, 15, 25, 0.85)',
        backdropFilter: 'blur(16px)',
        borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
        padding: '18px 0'
      }}>
        <div className="container" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            {client.logoUrl ? (
              <img src={client.logoUrl} alt={client.name} style={{ height: 38, objectFit: 'contain' }} />
            ) : (
              <div style={{
                width: 38,
                height: 38,
                borderRadius: 10,
                background: client.primaryColor,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 900,
                fontSize: 18,
                color: '#fff'
              }}>
                {client.name.charAt(0)}
              </div>
            )}
            <div>
              <h2 style={{ fontSize: 18, fontWeight: 800, margin: 0, letterSpacing: '-0.02em' }}>{client.name}</h2>
              <span style={{ fontSize: 11, color: '#94a3b8' }}>{client.tagline}</span>
            </div>
          </div>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            {client.phone && (
              <a href={\`tel:\${client.phone}\`} style={{ fontSize: 13, color: '#94a3b8' }}>{client.phone}</a>
            )}
            {client.whatsapp && (
              <a
                href={\`https://wa.me/\${client.whatsapp.replace(/[^0-9]/g, '')}?text=Hi%2C%20I%20am%20interested%20in%20your%20offerings.\`}
                target="_blank"
                rel="noreferrer"
                className="btn-primary"
              >
                Inquire on WhatsApp
              </a>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section style={{
        padding: '100px 0 80px',
        background: \`radial-gradient(ellipse at 50% 0%, \${client.primaryColor}22 0%, transparent 70%)\`,
        textAlign: 'center'
      }}>
        <div className="container">
          <span className="badge">Official Client Portal</span>
          <h1 style={{
            fontSize: 'clamp(2.5rem, 5vw, 4rem)',
            fontWeight: 900,
            lineHeight: 1.1,
            marginBottom: 20,
            letterSpacing: '-0.03em'
          }}>
            {client.name}
          </h1>
          <p style={{
            fontSize: 18,
            color: '#94a3b8',
            maxWidth: 680,
            margin: '0 auto 36px',
            lineHeight: 1.6
          }}>
            {client.description || client.tagline}
          </p>
          <div style={{ display: 'flex', justifyContent: 'center', gap: 16 }}>
            {client.whatsapp && (
              <a
                href={\`https://wa.me/\${client.whatsapp.replace(/[^0-9]/g, '')}\`}
                target="_blank"
                rel="noreferrer"
                className="btn-primary"
              >
                Get in Touch
              </a>
            )}
            {client.email && (
              <a
                href={\`mailto:\${client.email}\`}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  padding: '12px 24px',
                  borderRadius: 9999,
                  border: '1px solid rgba(255, 255, 255, 0.15)',
                  fontSize: 14,
                  fontWeight: 600,
                  color: '#cbd5e1'
                }}
              >
                Send Email
              </a>
            )}
          </div>
        </div>
      </section>

      {/* About Us & Stats Section */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.05)', background: 'rgba(255, 255, 255, 0.01)' }}>
        <div className="container">
          <div style={{ maxWidth: 800, margin: '0 auto', textAlign: 'center', marginBottom: 48 }}>
            <span className="badge">Heritage & Excellence</span>
            <h2 style={{ fontSize: 32, fontWeight: 800, margin: '12px 0 16px' }}>
              {SITE_CONFIG.content?.aboutTitle || 'About Our Organization'}
            </h2>
            <p style={{ fontSize: 16, color: '#94a3b8', lineHeight: 1.7 }}>
              {SITE_CONFIG.content?.aboutContent || client.description || client.tagline}
            </p>
          </div>

          {/* Stats Counters */}
          {SITE_CONFIG.content?.stats && SITE_CONFIG.content.stats.length > 0 && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 20, textAlign: 'center' }}>
              {SITE_CONFIG.content.stats.map((st, i) => (
                <div key={i} style={{ padding: '24px 16px', borderRadius: 14, background: 'rgba(255, 255, 255, 0.02)', border: '1px solid rgba(255, 255, 255, 0.06)' }}>
                  <div style={{ fontSize: 32, fontWeight: 900, color: client.primaryColor, marginBottom: 4 }}>{st.value}</div>
                  <div style={{ fontSize: 12, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>{st.label}</div>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Products / Offerings Section with Multiple Images Support */}
      {products && products.length > 0 && (
        <section style={{ padding: '80px 0 100px', borderTop: '1px solid rgba(255, 255, 255, 0.05)' }}>
          <div className="container">
            <div style={{ textAlign: 'center', marginBottom: 48 }}>
              <span className="badge">Featured Catalog</span>
              <h2 style={{ fontSize: 32, fontWeight: 800 }}>Products & Collections</h2>
            </div>
            
            <div className="product-grid">
              {products.map((prod, idx) => (
                <ProductCard key={prod.id || idx} prod={prod} client={client} />
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Footer */}
      <footer style={{
        borderTop: '1px solid rgba(255, 255, 255, 0.08)',
        background: '#070a10',
        padding: '60px 0 32px'
      }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 40, marginBottom: 48 }}>
            <div>
              <h3 style={{ fontSize: 18, fontWeight: 800, marginBottom: 12 }}>{client.name}</h3>
              <p style={{ fontSize: 13, color: '#94a3b8', lineHeight: 1.6 }}>{client.description || client.tagline}</p>
            </div>
            <div>
              <h4 style={{ fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#64748b', marginBottom: 16 }}>Contact</h4>
              <p style={{ fontSize: 13, color: '#cbd5e1', marginBottom: 8 }}>{client.address}</p>
              <p style={{ fontSize: 13, color: '#cbd5e1', marginBottom: 8 }}><a href={\`tel:\${client.phone}\`}>{client.phone}</a></p>
              <p style={{ fontSize: 13, color: '#cbd5e1' }}><a href={\`mailto:\${client.email}\`}>{client.email}</a></p>
            </div>
          </div>
          <div style={{
            borderTop: '1px solid rgba(255, 255, 255, 0.05)',
            paddingTop: 24,
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: 12,
            color: '#64748b'
          }}>
            <span>&copy; {new Date().getFullYear()} {client.name}. All rights reserved.</span>
            <span>Generated with Agency Template Studio</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
`;
  zip.file('src/App.jsx', appJsx);

  // 9. Generate README.md
  const readmeMd = `# ${clientBrand.name || projectName}

Independent client website generated from **${template.title}** (${template.tierLabel}).

## 🚀 Quick Start

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run development server:
\`\`\`bash
npm run dev
\`\`\`

3. Build for production:
\`\`\`bash
npm run build
\`\`\`

## 🌐 Deployment Instructions

### Deploy to Vercel
1. Push this repository to GitHub or GitLab.
2. Go to [vercel.com](https://vercel.com) and import the repository.
3. Framework Preset: **Vite**
4. Root Directory: \`./\`
5. Click **Deploy**.

### Deploy to Netlify
1. Drag and drop the \`dist\` folder (after running \`npm run build\`) into [Netlify Drop](https://app.netlify.com/drop).
2. Or connect to Git with build command \`npm run build\` and publish directory \`dist\`.

### Deploy to Static Hosting / Apache / Nginx
Upload the built \`dist/\` folder contents directly to your web server root (\`public_html\` or \`/var/www/html\`).
`;
  zip.file('README.md', readmeMd);

  // Generate and download zip
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName}-standalone.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);

  return true;
}
